new comparer
pepelev/Zenki pull request #2
Opened 2023-05-01 16:47 UTC by wizzem1110

2023-05-01 17:29 UTC, pepelev requested changes

2023-05-01 17:29 UTC, pepelev commented on src/UI/ResultOrder.cs
> +            if (queryCount - k < max) break;
Можно вложить это условие в условие цикла

2023-05-01 17:29 UTC, pepelev commented on src/UI/ResultOrder.cs
> +        var queryCount = query.Length;
`query` - `string`. У строки нет понятия количества, есть понятие длины. Поэтому переменная путает

2023-05-01 17:29 UTC, pepelev commented on src/UI/ResultOrder.cs
> +            if (query.Length - k <= max) break;
Тут тоже можно вложить условие в условие цикла

2023-05-01 17:29 UTC, pepelev commented on src/UI/ResultOrder.cs
> +
Если `result` получился ненулевой, то можно не вычислять триграммы и не пересекать их

2023-05-01 17:29 UTC, pepelev commented on src/UI/ResultOrder.cs
> +        var trigrams = Trigram.StringToTrigrams(query).ToList();
Так мы на каждое сравнение можем вычислять триграммы `query`. Можно этого избежать

2023-05-01 17:29 UTC, pepelev commented on src/UI/ResultOrder.cs
>          const int dummy = 0;
Это вместе с комментарием можно почистить

2023-05-01 17:29 UTC, pepelev commented on src/Zenki.Tests/ResultOrderShould.cs
> +        comp.Compare(x, y).Should().Be(-1);
Сложно воспринимать результат сравнения как `-1`, `0` или `1`. Нужно помнить что они значат.
Здесь тест лучше оформить так:
1. создать лист из элементов
2. отсортировать с помощью `ResultOrder`
3. проверить результирующий порядок элементов `list.Should().Equal(x, y);`

2023-05-01 17:29 UTC, pepelev commented on src/Zenki.Tests/ResultOrderShould.cs
> +    public void CompareCorrectly()
Тест падает

2023-05-01 17:29 UTC, pepelev commented on src/Zenki.Tests/ResultOrderShould.cs
> +        var comp = new ResultOrder(query);
Какой же это `comp`, если это порядок.

Название `IComparer` не отражает понятие, оно отражает действие. Лучше называть по сути, а не по действию. Это более человечный и менее машинный подход

2023-05-01 17:37 UTC, pepelev commented on src/UI/ResultOrder.cs
>  using System.Text;
Давай почистим лишний `using`

2023-05-03 16:58 UTC, pepelev commented on src/UI/ResultOrder.cs
> +        for (var k = 0; k < queryLength && max <= queryLength - k; k++)
Первая часть условия стала ненужной. В правой половине выражения `k` можно перенести влево, а все остальное вправо

2023-05-03 16:58 UTC, pepelev commented on src/UI/ResultOrder.cs
> +
Давай пробелы уберем. Это можно сделать подчисткой кода решарпером CTRL+ALT+F

2023-05-03 16:58 UTC, pepelev commented on src/UI/ResultOrder.cs
> +            if (query.Length - k <= max) break;
Аналогично и тут появилась избыточность

2023-05-03 16:58 UTC, pepelev commented on src/UI/ResultOrder.cs
> +        if (result == 0)
Можно пойти от обратного - если результат ненулевой вернуть его. Это сократит вложенность и позволит не просматривать весь метод чтобы понять что будет при расхождении `GetMaxSubsequence` для `x` и для `y`

2023-05-04 12:02 UTC, wizzem1110 commented on src/UI/ResultOrder.cs
> +        if (result == 0)
развернул ифы, однако теперь 2 (потенциально 3) одинаковых строки

2023-05-04 12:02 UTC, wizzem1110 commented on src/UI/ResultOrder.cs
> +        for (var k = 0; k < queryLength && max <= queryLength - k; k++)
fixed

2023-05-04 12:02 UTC, wizzem1110 commented on src/UI/ResultOrder.cs
> +            if (query.Length - k <= max) break;
fixed

2023-05-04 12:53 UTC, pepelev requested changes

2023-05-04 12:53 UTC, pepelev commented on src/UI/ResultOrder.cs
> +        for (var k = 0; max + k >= query.Length; k++)
С таким условием при `query.Length > 0` цикл не выполнится ни разу. Что-то потеряли при рефакторинге

2023-05-04 14:12 UTC, wizzem1110 commented on src/UI/ResultOrder.cs
> +        for (var k = 0; max + k >= query.Length; k++)
fixed

2023-05-04 16:17 UTC, merged