sprache
pepelev/Zenki pull request #5
Opened 2023-06-16 16:02 UTC by wizzem1110

2023-06-16 18:08 UTC, pepelev requested changes
Ништяково! Все по делу. Есть только поверхностные замечания.

Гитхаб говорит, что будут конфликты при влитии. Давай вольем ветку `main` в `field-filters` и решим конфликты. Если непонятно что делать - пиши, сделаем вместе

2023-06-16 18:08 UTC, pepelev commented on src/UI/FieldFilter.cs
> +    private static readonly Parser<FieldFilter> FieldParser =
Давай заведем статический класс `QuerySyntax` и будем складывать туда все парсеры как публичные свойства, в том числе и этот парсер

2023-06-16 18:08 UTC, pepelev commented on src/UI/FieldFilter.cs
> +    public static FieldFilter SpracheParseField(string str) => FieldParser.Parse(str);
Так класс `FieldFilter` начинает заниматься двумя вещами: фильтрация и парсинг себя из строки. Это можно трактовать как нарушение Single Responsibility Principle (см. 10 главу Чистого кода).

Пусть `QuerySyntax` дает наружу парсеры, которыми можно превратить строку в фильтр

2023-06-16 18:08 UTC, pepelev commented on src/UI/FieldFilter.cs
> +    public override bool Equals(object? obj)
Про то как писать сравнение объектов смотри статьи:
- https://habr.com/ru/articles/314328/
- https://habr.com/ru/articles/314500/

2023-06-16 18:08 UTC, pepelev commented on src/UI/FieldFilter.cs
> +        var b = (FieldFilter)obj!;
`!` не спасет от того, что в качестве `obj` могут передать `null`. Если будет так, то на следующей строке при обращении к `b.field` полетит `NullReferenceException`.

Вообще решарпер умеет автоматически создавать код для Equals и GetHashCode. Alt+Insert -> Equality members. 
Операторы пока не надо перегружать, и `IEquatable` тоже давай пока не будем трогать.

2023-06-16 18:08 UTC, pepelev commented on src/UI/UI.csproj
> +        <PackageReference Include="Sprache" Version="3.0.0-develop-00049" />
Версии с дефисом и строкой после `X.Y.Z` считаются [пререлизными](https://semver.org/spec/v1.0.0.html#spec-item-4). Давай возьмем не пререлизную версию

2023-06-17 20:37 UTC, wizzem1110 commented on src/UI/FieldFilter.cs
> +    private static readonly Parser<FieldFilter> FieldParser =
fixed

2023-06-17 20:37 UTC, wizzem1110 commented on src/UI/FieldFilter.cs
> +    public static FieldFilter SpracheParseField(string str) => FieldParser.Parse(str);
fixed

2023-06-17 20:39 UTC, wizzem1110 commented on src/UI/FieldFilter.cs
> +    public override bool Equals(object? obj)
fixed

2023-06-17 20:39 UTC, wizzem1110 commented on src/UI/FieldFilter.cs
> +        var b = (FieldFilter)obj!;
~fixed

2023-06-17 20:39 UTC, wizzem1110 commented on src/UI/UI.csproj
> +        <PackageReference Include="Sprache" Version="3.0.0-develop-00049" />
fixed

2023-06-18 12:12 UTC, merged